services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=edusmart_db'
      - 'POSTGRES_USER=harveyj'
      - 'POSTGRES_PASSWORD=harvysql'
    ports:
      - '5432:5432'