server.port = 8090

# Data JPA
spring.datasource.url=jdbc:postgresql://localhost:5432/edusmart_db
spring.datasource.username=harveyj
spring.datasource.password=harvysql
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Soporte para que Spring controle el ciclo de Docker Compose
spring.docker.compose.enabled=true
spring.docker.compose.lifecycle-management=start-and-stop

# LangChain4j Config Base para pruebas (demo)
langchain4j.open-ai.chat-model.api-key=demo
langchain4j.open-ai.chat-model.log-requests=true
langchain4j.open-ai.chat-model.log-responses=true